// Code generated by MockGen. DO NOT EDIT.
// Source: secondary.go
//
// Generated by this command:
//
//	mockgen -source=secondary.go -destination=mock/secondary.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"

	model "github.com/antoinecrochet/transport-rennes-api/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDataProviderPort is a mock of DataProviderPort interface.
type MockDataProviderPort struct {
	ctrl     *gomock.Controller
	recorder *MockDataProviderPortMockRecorder
	isgomock struct{}
}

// MockDataProviderPortMockRecorder is the mock recorder for MockDataProviderPort.
type MockDataProviderPortMockRecorder struct {
	mock *MockDataProviderPort
}

// NewMockDataProviderPort creates a new mock instance.
func NewMockDataProviderPort(ctrl *gomock.Controller) *MockDataProviderPort {
	mock := &MockDataProviderPort{ctrl: ctrl}
	mock.recorder = &MockDataProviderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProviderPort) EXPECT() *MockDataProviderPortMockRecorder {
	return m.recorder
}

// SearchUpcomingPublicTransports mocks base method.
func (m *MockDataProviderPort) SearchUpcomingPublicTransports(search model.Search) (model.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUpcomingPublicTransports", search)
	ret0, _ := ret[0].(model.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUpcomingPublicTransports indicates an expected call of SearchUpcomingPublicTransports.
func (mr *MockDataProviderPortMockRecorder) SearchUpcomingPublicTransports(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUpcomingPublicTransports", reflect.TypeOf((*MockDataProviderPort)(nil).SearchUpcomingPublicTransports), search)
}
